In [3]:
from glob import glob
from tqdm import tqdm
import os
from path import Path
import pandas as pd

os.getcwd()

'C:\\Users\\MANDEEP SINGH SHERRY'

In [4]:
obj1_files = glob('Desktop\Files for task 1 and task 6\Object 1\*')

df = pd.DataFrame()
for i in tqdm(obj1_files):
    df = pd.concat([df, pd.read_excel(i, header=None).iloc[:,6:]])

100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:17<00:00,  1.98s/it]

In [5]:
df['label'] = 1
df.shape
df.head()

,6,7,8,9,10,11,12,13,14,15,...,3397,3398,3399,3400,3401,3402,3403,3404,3405,label
0,0.000384,0.000640,0.001408,0.001792,0.001408,0.001280,0.001920,0.002304,0.001920,0.002688,...,-0.010879,-0.011519,-0.011391,-0.011647,-0.011775,-0.011391,-0.011263,-0.010623,-0.009215,1
1,-0.003712,-0.003968,-0.004608,-0.004992,-0.005632,-0.006016,-0.006271,-0.006016,-0.006399,-0.006271,...,-0.006271,-0.006016,-0.005760,-0.004864,-0.003840,-0.002816,-0.002176,-0.001920,-0.001792,1
2,-0.000640,-0.000512,-0.000768,-0.000640,-0.000768,0.000000,-0.000256,-0.000256,-0.000768,-0.001024,...,-0.006911,-0.006911,-0.006783,-0.006911,-0.006399,-0.006016,-0.005376,-0.004352,-0.003328,1
3,-0.001152,-0.000896,-0.000384,0.000128,0.000000,-0.000128,-0.000768,-0.001280,-0.001280,-0.000896,...,0.013183,0.013695,0.013951,0.014463,0.014463,0.014335,0.013823,0.013311,0.012159,1
4,-0.002176,-0.001920,-0.001024,-0.000640,-0.000512,-0.000640,-0.000896,-0.000896,-0.000896,-0.001536,...,-0.009471,-0.008703,-0.007679,-0.006271,-0.006016,-0.005504,-0.004352,-0.002944,-0.001920,1

In [6]:
obj2_files = glob('Desktop\Files for task 1 and task 6\Object 2\*')

df_2 = pd.DataFrame()
for i in tqdm(obj2_files):
    df_2 = pd.concat([df_2, pd.read_excel(i, header=None).iloc[:,6:]])

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:11<00:00,  2.91s/it]

In [9]:
df_2['label'] = 0
df_2.shape
df_2.head()

,6,7,8,9,10,11,12,13,14,15,...,3397,3398,3399,3400,3401,3402,3403,3404,3405,label
0,-0.001408,-0.001024,-0.001024,-0.001664,-0.002304,-0.001664,-0.001920,-0.001280,-0.000512,-0.000896,...,0.009855,0.009727,0.009727,0.009599,0.009343,0.009343,0.008703,0.008447,0.007039,0
1,-0.000768,-0.000896,-0.000640,-0.000640,-0.000896,-0.001152,-0.001536,-0.002048,-0.001664,-0.001408,...,0.008191,0.008063,0.008319,0.008831,0.009215,0.008959,0.008319,0.007679,0.007039,0
2,-0.001792,-0.001792,-0.001280,-0.000768,-0.000896,-0.000640,-0.000384,-0.000896,-0.001408,-0.001664,...,0.009087,0.010239,0.010495,0.010367,0.010111,0.008959,0.008703,0.008447,0.007551,0
3,0.000000,-0.000128,-0.000384,-0.000896,-0.001152,-0.001408,-0.001792,-0.002304,-0.001920,-0.001536,...,0.008959,0.009087,0.009599,0.009471,0.008831,0.008959,0.008575,0.007295,0.006911,0
4,-0.000512,-0.000640,-0.001280,-0.001536,-0.001536,-0.001408,-0.001280,-0.001408,-0.001024,-0.001152,...,0.008703,0.008703,0.008703,0.008575,0.008447,0.007807,0.007295,0.006911,0.006271,0

In [19]:
## Merge two data sets

merge_df = pd.concat([df, df_2])

# Train-Test Split

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(merge_df.iloc[:,:3400], merge_df['label'], test_size=0.2)

# Define and Train Model

In [21]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

### Check Metrics, like Accuracy

In [22]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)
y_train.value_counts()
y_test.value_counts()

1    68
0    35
Name: label, dtype: int64